name: Deploy Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.8.2
      
      - name: Authenticate with gcloud
        run: echo "$GCP_SA_KEY" > /tmp/gcp-credentials.json
      
      - name: Configure gcloud CLI
        run: |
          gcloud auth activate-service-account --key-file=/tmp/gcp-credentials.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
      
      - name: Terraform init
        run: terraform init
      
      - name: Terraform plan
        run: terraform plan -out=tfplan
      
      - name: Terraform apply
        run: terraform apply -auto-approve tfplan
