name: 'Terraform Apply'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    needs: terraform_tests
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3.1.1
      with:
        terraform_version: 1.8.5

    - name: Clean Terraform directory
      run: |
        rm -rf .terraform
        rm -f .terraform.lock.hcl

    - name: Terraform Init
      run: terraform init -upgrade
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    - name: Terraform workspace select
      run: terraform workspace select prod || terraform workspace new prod
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    - name: Terraform Plan
      run: terraform plan -out=plan.tfplan && terraform show -json plan.tfplan > tfplan.json
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve plan.tfplan
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
