name: 'Terraform PR'

on:
  pull_request:
    branches:
      - main
    types: [opened]

jobs:
  terraform_tests:
    name: 'Terraform Tests'
    uses: ./.github/workflows/terraform-tests.yml
    with:
      gcp-sa-key: ${{ secrets.GCP_SA_KEY }}  